Revert "Revert workaround for SWDEV-344283 (#1080)"
This reverts commit 0d65a3fcddcdbf9f9bafcbcd0f96630ff9dc816a because it
broke PyTorch build for ROCm5.2 with the following error:

```
/var/lib/jenkins/pytorch/aten/src/ATen/native/hip/linalg/HIPSolver.cpp:789:65: error: invalid conversion from ‘const float*’ to ‘float*’ [-fpermissive]
  789 |   TORCH_CUSOLVER_CHECK(hipsolverDnSpotrs(handle, uplo, n, nrhs, A, lda, B, ldb, devInfo));
      |                                                                 ^
      |                                                                 |
      |                                                                 const float*
```