[rocm6.3_internal_testing][ROCm] Fix largeIndexBlockSize (#1657)
On ROCm, hipification converts std::min to ::min, but ::min is not
returning the right result. This impacts index_add_ operation on a large
tensor, we end up picking the large values instead of max supported
block size (128). This leads to GPU accessing memory out of bounds.

While we wait for ::min to be fixed, we can use < operator to compare
instead of relying on ::min.

Example Code w/ failure:
```
D=6144
hidden_states = torch.zeros([16384, 6144],           device="cuda:0", dtype=torch.bfloat16)
index         = torch.randint(0, 16384, (1, 32, 16384), device="cuda:0", dtype=torch.int64)
output        = torch.empty([1, 32, 16384, 6144],    device="cuda:0", dtype=torch.bfloat16)
hidden_states.index_add_(0, index.view(-1), output.view(-1, D))
```


```
Traceback (most recent call last):
RuntimeError: HIP error: invalid configuration argument
```

(cherry picked from commit c0266dbfa44c6904a6d504c911f121fe774db184)