[release/2.2] skip test_typing if numpy less then 1.21 (#1563) (#1567)
Warning!!! 
run_test.py failed if nothing to do in release/2.2 (`./run_test.py -i
test_typing` if test_typing is banned)
```
+ f"to prioritize ({(num_tests_found / len(tests)):.2%}%)"
ZeroDivisionError: division by zero
```
Skip test_typing to avoid `Error importing plugin
"numpy.typing.mypy_plugin": No module named 'numpy.typing.mypy_plugin'`
It happens because we have numpy==1.20.3 in some of our images. But
`mypy` can be used only witn numpy>=1.21
We have numpy==1.20.3 in our images with python3.9

Will check numpy version in run_tests.py and add test_typing to
ROCM_BLOCKLIST if numpy version less then 1.21

Fix https://github.com/ROCm/frameworks-internal/issues/8497

(cherry picked from commit 3b54c4556df4682e4a7b71d1006c2984071ea212)