Cherry-picked from:
Author: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>
Date:   Fri Jan 20 04:38:07 2023 +0000

    [ROCm] Fix distributed tests failure

    Distributed tests fails due to  AttributeError: 'torch._C._distributed_c10d.ProcessGroup'
    object has no attribute '_set_backend' , when running distributed/test_c10d_spawn_gloo.py
    This leads to tests not progressing resulting in hang.
    Check if the attribute '_set_backend' exists before using it.

    Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>